### PR TITLE
migration: Prettier `v2.2.x` to `v2.4.x`

### PR DESCRIPTION
**Pull request by yukinoda**
# <Feature Title>

## What are you adding?
- upgraded prettier `v2.2.x` to `v2.4.x` 90bd97f
- `jsxBracketSameLine` is deprecated, renamed to [`bracketSameLine`](https://prettier.io/blog/2021/09/09/2.4.0.html#replace-jsxbracketsameline-option-with-bracketsameline-option-11006httpsgithubcomprettierprettierpull11006-by-kurtztechhttpsgithubcomkurtztech) 90bd97f
- fixed no files matching 602758f

### CODE REVIEW

**Comment by yukinoda** [comment]
@mvn-binhnguyen-hn cc: @jacksonjp 
Can anyone in your team using windows check if this changes 602758f work?

**Comment by yannde** [comment]
@yukinoda 
I had the following errors when running on windows
```
Failed to compile.

src\components\atoms\DebouncedInput\DebouncedInput.tsx
  Line 41:28:  Replace `⏎····(persistOnChange?:·React.ChangeEventHandler)·=>·(e:·React.ChangeEvent` with `·(persistOnChange?:·React.ChangeEventHandler)·=>·(⏎····e:·React.ChangeEvent⏎··`  prettier/prettier
  Line 43:1:   Delete `··`
                                               prettier/prettier
  Line 44:1:   Replace `······` with `····`
                                               prettier/prettier
  Line 45:1:   Delete `··`
                                               prettier/prettier
  Line 46:1:   Delete `··`
                                               prettier/prettier

src\features\localization\helpers\localization.helpers.ts
  Line 9:10:  Replace `·translation,·translationMeta,·availableLanguages·}·=⏎···` with `⏎····translation,⏎····translationMeta,⏎····availableLanguages,⏎··}·=`  prettier/prettier

src\hooks\useSearchParams.ts
  Line 45:27:  Insert `(`  prettier/prettier
  Line 48:24:  Insert `)`  prettier/prettier
```

**Comment by yukinoda** [comment]
### On Windows by @yannde 

```
 "format": "prettier 'src/**/*.{ts,tsx,json,scss,css}' --write",
 "lint": "eslint 'src/**/*.{ts,tsx}' --fix --quiet",
```
Gives an error

```
"format": "prettier src/**/*.{ts,tsx,json,scss,css} --write",
"lint": "eslint src/**/*.{ts,tsx} --fix --quiet",
```
Is OK

### On MacOS by me

```
 "format": "prettier 'src/**/*.{ts,tsx,json,scss,css}' --write",
 "lint": "eslint 'src/**/*.{ts,tsx}' --fix --quiet",
```
Is OK

```
"format": "prettier src/**/*.{ts,tsx,json,scss,css} --write",
"lint": "eslint src/**/*.{ts,tsx} --fix --quiet",
```
Gives an error

**Comment by yukinoda** [comment]
> ### On Windows by @yannde
> ```
>  "format": "prettier 'src/**/*.{ts,tsx,json,scss,css}' --write",
>  "lint": "eslint 'src/**/*.{ts,tsx}' --fix --quiet",
> ```
> 
> Gives an error
> 
> ```
> "format": "prettier src/**/*.{ts,tsx,json,scss,css} --write",
> "lint": "eslint src/**/*.{ts,tsx} --fix --quiet",
> ```
> 
> Is OK
> 
> ### On my MacOS
> ```
>  "format": "prettier 'src/**/*.{ts,tsx,json,scss,css}' --write",
>  "lint": "eslint 'src/**/*.{ts,tsx}' --fix --quiet",
> ```
> 
> Is OK
> 
> ```
> "format": "prettier src/**/*.{ts,tsx,json,scss,css} --write",
> "lint": "eslint src/**/*.{ts,tsx} --fix --quiet",
> ```
> 
> Gives an error

I will bring this as a separate issue and revert 602758f

**Review by yukinoda — COMMENTED** [review]
ready to review

**Review by jacksonjp — APPROVED** [review]

**Pull request merged**
